/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.DBAccess;
import database.DBConnection;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JPanel;

/**
 *
 * @author NKS
 */
public class AdminMainFrame extends javax.swing.JFrame {

    int currStatus = 1; //1 - Overview, 2 - Budget
    
    public AdminMainFrame() {
        initComponents();
        lblCurrUser.setText("Welcome! \n" + DBAccess.currentUser);
        
        textFieldFocus();
        
        refreshUserTable();
        
        this.setLocationRelativeTo(null); //Locate your app in the middle of screen
    }
    
    void refreshUserTable() {
        
        DBAccess.fetchUserOverviewTable();
        tblUserList.setModel(DBAccess.overviewUserTableModel);
        
    }
    
    void switchNav(JPanel nextSelect) {
        
        switch(currStatus) {
            case 1:
                overviewPanel.setVisible(false);
                overviewSelect.setBackground(new Color(0,190,240));
                nextSelect.setBackground(new Color(0,242,252));
                break;
            case 2:
                settingsPanel.setVisible(false);
                settingsSelect.setBackground(new Color(0,190,240));
                nextSelect.setBackground(new Color(0,242,252));
                break;
            default:
              // code block
                System.out.print("Not valid selection!");
          }   
            
    }

    private void textFieldFocus(){
        
        txtFSearch.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                
                if (txtFSearch.getText().equals("Username")) {
                    txtFSearch.setText("");
                    txtFSearch.setForeground(Color.black);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txtFSearch.getText().isEmpty()) {
                    txtFSearch.setText("Username");
                    txtFSearch.setForeground(Color.gray);
                }
            }
        });
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogUserDetails = new javax.swing.JDialog();
        panelDialog = new javax.swing.JPanel();
        lblUserID = new javax.swing.JLabel();
        txtFUserID = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtFUsername = new javax.swing.JTextField();
        txtFPassword = new javax.swing.JTextField();
        txtFEmail = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        overviewSelect = new javax.swing.JPanel();
        logoOverview = new javax.swing.JLabel();
        labelOverview = new javax.swing.JLabel();
        settingsSelect = new javax.swing.JPanel();
        logoSettings = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userPanel = new javax.swing.JPanel();
        lblCurrUser = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        layerPanelAdmin = new javax.swing.JLayeredPane();
        overviewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserList = new javax.swing.JTable();
        txtFSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lblUserInfo = new javax.swing.JLabel();
        btnShowAll = new javax.swing.JButton();
        settingsPanel = new javax.swing.JPanel();
        panelEditPass = new javax.swing.JPanel();
        lblOldPassword = new javax.swing.JLabel();
        passFOldPass = new javax.swing.JPasswordField();
        passFNewPass = new javax.swing.JPasswordField();
        lblNewPassword = new javax.swing.JLabel();
        btnSubmitPass = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        dialogUserDetails.setMinimumSize(new java.awt.Dimension(410, 390));
        dialogUserDetails.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                dialogUserDetailsWindowLostFocus(evt);
            }
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
        });
        dialogUserDetails.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogUserDetailsWindowClosing(evt);
            }
        });

        lblUserID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserID.setText("User ID :");

        txtFUserID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFUserID.setEnabled(false);

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("Username : ");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password : ");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email : ");

        txtFUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtFPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtFEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDialogLayout = new javax.swing.GroupLayout(panelDialog);
        panelDialog.setLayout(panelDialogLayout);
        panelDialogLayout.setHorizontalGroup(
            panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDialogLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDialogLayout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDialogLayout.createSequentialGroup()
                        .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDialogLayout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDialogLayout.createSequentialGroup()
                        .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
            .addGroup(panelDialogLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDialogLayout.setVerticalGroup(
            panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDialogLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout dialogUserDetailsLayout = new javax.swing.GroupLayout(dialogUserDetails.getContentPane());
        dialogUserDetails.getContentPane().setLayout(dialogUserDetailsLayout);
        dialogUserDetailsLayout.setHorizontalGroup(
            dialogUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogUserDetailsLayout.setVerticalGroup(
            dialogUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogUserDetailsLayout.createSequentialGroup()
                .addComponent(panelDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dialogUserDetails.setLocationRelativeTo(null); //Locate your app in the middle of screen

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(83, 154, 231));

        overviewSelect.setBackground(new java.awt.Color(0, 242, 252));
        overviewSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                overviewSelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                overviewSelectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                overviewSelectMousePressed(evt);
            }
        });

        logoOverview.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoOverview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoOverview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vectors/overview-35.png"))); // NOI18N

        labelOverview.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelOverview.setForeground(new java.awt.Color(30, 33, 122));
        labelOverview.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelOverview.setText("Overview");

        javax.swing.GroupLayout overviewSelectLayout = new javax.swing.GroupLayout(overviewSelect);
        overviewSelect.setLayout(overviewSelectLayout);
        overviewSelectLayout.setHorizontalGroup(
            overviewSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overviewSelectLayout.setVerticalGroup(
            overviewSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        settingsSelect.setBackground(new java.awt.Color(0, 190, 240));
        settingsSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsSelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsSelectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsSelectMousePressed(evt);
            }
        });

        logoSettings.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vectors/settings-35.png"))); // NOI18N

        settingsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(30, 33, 122));
        settingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settingsLabel.setText("Settings");

        javax.swing.GroupLayout settingsSelectLayout = new javax.swing.GroupLayout(settingsSelect);
        settingsSelect.setLayout(settingsSelectLayout);
        settingsSelectLayout.setHorizontalGroup(
            settingsSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsSelectLayout.setVerticalGroup(
            settingsSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCurrUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrUser, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overviewSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        bottomPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1000, 30));

        layerPanelAdmin.setLayout(new java.awt.CardLayout());

        overviewPanel.setBackground(new java.awt.Color(255, 255, 255));

        tblUserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUserList.setEnabled(false);
        tblUserList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUserList);

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearch.setText("Username : ");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblUserInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUserInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserInfo.setText("Users Info");

        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addComponent(txtFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShowAll)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        layerPanelAdmin.add(overviewPanel, "card2");

        settingsPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelEditPass.setBackground(new java.awt.Color(204, 255, 255));
        panelEditPass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Change Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblOldPassword.setText("Old Password :");

        lblNewPassword.setText("New Password :");

        btnSubmitPass.setText("Submit");
        btnSubmitPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditPassLayout = new javax.swing.GroupLayout(panelEditPass);
        panelEditPass.setLayout(panelEditPassLayout);
        panelEditPassLayout.setHorizontalGroup(
            panelEditPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditPassLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(panelEditPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOldPassword)
                    .addComponent(lblNewPassword))
                .addGap(29, 29, 29)
                .addGroup(panelEditPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passFNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passFOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(panelEditPassLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnSubmitPass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditPassLayout.setVerticalGroup(
            panelEditPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditPassLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelEditPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passFOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOldPassword))
                .addGap(49, 49, 49)
                .addGroup(panelEditPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPassword)
                    .addComponent(passFNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnSubmitPass)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnLogout))
                    .addComponent(panelEditPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelEditPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(50, 50, 50))
        );

        layerPanelAdmin.add(settingsPanel, "card3");

        getContentPane().add(layerPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 820, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void overviewSelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewSelectMousePressed
        // TODO add your handling code here:

        switchNav(overviewSelect);
        overviewPanel.setVisible(true);
        currStatus = 1;
       
    }//GEN-LAST:event_overviewSelectMousePressed

    private void overviewSelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewSelectMouseExited
        // TODO add your handling code here:
        if (currStatus != 1)
        overviewSelect.setBackground(new Color(0,190,240));
    }//GEN-LAST:event_overviewSelectMouseExited

    private void overviewSelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewSelectMouseEntered
        // TODO add your handling code here:
        if (currStatus != 1)
        overviewSelect.setBackground(new Color(0,242,252));
    }//GEN-LAST:event_overviewSelectMouseEntered

    private void settingsSelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsSelectMousePressed
        // TODO add your handling code here:
        switchNav(settingsSelect);
        currStatus = 2;

        settingsPanel.setVisible(true);
    }//GEN-LAST:event_settingsSelectMousePressed

    private void settingsSelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsSelectMouseExited
        // TODO add your handling code here:
        if (currStatus != 2)
        settingsSelect.setBackground(new Color(0,190,240));
    }//GEN-LAST:event_settingsSelectMouseExited

    private void settingsSelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsSelectMouseEntered
        // TODO add your handling code here:
        if (currStatus != 2)
        settingsSelect.setBackground(new Color(0,242,252));
    }//GEN-LAST:event_settingsSelectMouseEntered

    private void btnSubmitPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPassActionPerformed
        // TODO add your handling code here:

        String pwOld = new String(passFOldPass.getPassword());
        String pwNew = new String (passFNewPass.getPassword());

        if(pwOld.equals(pwNew)){
            System.out.println("New password cannot be same as old password!");
        }else{
            DBAccess.changePW(pwNew, pwOld);
        }

    }//GEN-LAST:event_btnSubmitPassActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        DBAccess.getSpecificUsername(txtFSearch.getText());
        tblUserList.setModel(DBAccess.overviewUserTableModel);
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblUserListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserListMouseClicked
        // TODO add your handling code here:
        
        int row = tblUserList.rowAtPoint(evt.getPoint());
        
        String dataV = tblUserList.getModel().getValueAt(row, 0).toString();
        
        System.out.println(dataV);
        
        String[] dataRow = new String[4];
        
        if (evt.getClickCount() == 2) {
//            int row = tableBudget.rowAtPoint(evt.getPoint()); //https://coderanch.com/t/343164/java/jTable-selectedRowIndex-mouse-click

            //get each column data/value
            for(int x = 0; x < 4; x++) {
                
                String value = tblUserList.getModel().getValueAt(row, x).toString();
                dataRow[x] = value;
            }
            
            txtFUserID.setText(dataRow[0]);
            txtFUsername.setText(dataRow[1]);
            txtFEmail.setText(dataRow[3]);
            txtFPassword.setText(dataRow[2]);
            
            this.setEnabled(false);
            dialogUserDetails.setVisible(true);
            
            
        }
    }//GEN-LAST:event_tblUserListMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        DBAccess.updateUserListTableRowValue(
                txtFUserID.getText(), 
                txtFUsername.getText(), 
                txtFEmail.getText(), 
                txtFPassword.getText()
        );
        
        this.setEnabled(true);
        refreshUserTable();
        dialogUserDetails.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        DBAccess.deleteUserListTableRowValue(txtFUserID.getText());
        
        this.setEnabled(true);
        refreshUserTable();
        dialogUserDetails.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        this.setEnabled(true);
        dialogUserDetails.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void dialogUserDetailsWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogUserDetailsWindowLostFocus
        // TODO add your handling code here:
        
        System.out.println("*******oiLOST FOCUS");
        dialogUserDetails.requestFocus();
        
        
    }//GEN-LAST:event_dialogUserDetailsWindowLostFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        DBConnection.close();
        System.out.println("Closing database connections");
    }//GEN-LAST:event_formWindowClosing

    private void dialogUserDetailsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogUserDetailsWindowClosing
        // TODO add your handling code here:
        this.setEnabled(true);
    }//GEN-LAST:event_dialogUserDetailsWindowClosing

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        
        refreshUserTable();
    }//GEN-LAST:event_btnShowAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnSubmitPass;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JDialog dialogUserDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelOverview;
    private javax.swing.JLayeredPane layerPanelAdmin;
    private javax.swing.JLabel lblCurrUser;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel logoOverview;
    private javax.swing.JLabel logoSettings;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JPanel overviewSelect;
    private javax.swing.JPanel panelDialog;
    private javax.swing.JPanel panelEditPass;
    private javax.swing.JPasswordField passFNewPass;
    private javax.swing.JPasswordField passFOldPass;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel settingsSelect;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tblUserList;
    private javax.swing.JTextField txtFEmail;
    private javax.swing.JTextField txtFPassword;
    private javax.swing.JTextField txtFSearch;
    private javax.swing.JTextField txtFUserID;
    private javax.swing.JTextField txtFUsername;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
